# Generated by Django 5.1.6 on 2025-02-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancerprediction',
            name='LUNG_CANCER',
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='ALCOHOL_CONSUMING',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='ALLERGY',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='ANXIETY',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='CHEST_PAIN',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='CHRONIC_DISEASE',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='COUGHING',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='FATIGUE',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='PEER_PRESSURE',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='SHORTNESS_OF_BREATH',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='SMOKING',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='SWALLOWING_DIFFICULTY',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='WHEEZING',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancerprediction',
            name='YELLOW_FINGERS',
            field=models.BooleanField(default=False),
        ),
    ]
